# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*/

environment:
  ModuleName: Infoblox
  ResourceGroupName: infobloxtesting
  location: SouthCentralUS
  IBAdminPassword:
    secure: +Yhi3I1uR1xjocdrPn5HGA==
  AzurePassword:
    secure:  YsJNS6K8bf+aQp94gs6CJA==
  AzureTenantID:
    secure:  9dde4IdsaFmMXI+c8qpfltOt1vXkebzQldt43KK3i8ips7SWYUw8M3Z0ueHZkJcx
  AzureAppLoginID:
    secure:  eeRsMl/TAFnKPf6nqz/GlZ1PRdvIj/QhgSOqWDalQAQy5o+4OW8J5bWrZAp+rp7McQ6C/GAgkr6ypF0vTmA4ysAYsCcwqwBOzIxze2KQwaI=
install:
 - ps: install-module Pester
 - ps: install-module AzureRM
build_script:
 - ps: . .\build.ps1

before_test:
# Build test environment in azure to run pester tests against
 - ps: . .\Tests\appveyor.testenv.ps1 -build
test_script:
# Test with native PS version
  - ps: . .\Tests\appveyor.pester.ps1 -Test
# Finalize pass - collect and upload results
  - ps: . .\Tests\appveyor.pester.ps1 -Finalize
after_test:
#destroy test environment in azure after tests are complete
 - ps: . .\Tests\appveyor.testenv.ps1 -destroy

 artifacts:
 - path: $(ModuleName)
